- name: test ansible
  remote_user: ec2-user
  become: true
  become_user: root
  become_method: sudo
  hosts: target
  
  vars:
    ansible_python_interpreter: /bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    
  pre_tasks:
    - name: wait for server
      wait_for_connection:
        timeout: 60
    - name: "install python 3."
      become: true
      yum:
        name: 'python3'
        state: latest
        update_cache: yes
    # - name: install python 3 for ansible
    #   become: true
    #   shell: |
    #     sudo yum install python3 -y

  #roles:
    #- print
    #- install_nodejs_ubuntu
    #- deploy_nodejs_ubuntu
    #- install_nodejs_amazon
    # - configure_server_amazon
    # - deploy_nodejs_amazon