version: 2.1
orbs:
#  node: 'circleci/node:4.1'
  slack: circleci/slack@4.1
  
defaults: &defaults
  docker: 
    - image: cimg/node:13.8.0
#  working_directory: ~/project
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      back-stack:
        type: string
      front-stack:
        type: string   
    steps:
      - run:
          name: Destroy back-end environments
          when: on_fail
          command: |
            aws cloudformation delete-stack \
            --stack-name <<parameters.back-stack>> \
            --region us-west-2
      - run:
          name: Destroy front-end environments
          when: on_fail
          command: |
            aws cloudformation delete-stack \
            --stack-name  <<parameters.front-stack>> \
            --region us-west-2

jobs:         
  deploy-backend: 
    docker:
      - image: python:3.10.5-alpine3.15 # cimg/python:3.10.5-node
    steps:
      - checkout
      - add_ssh_keys: 
          fingerprints: ["3c:f4:1e:07:f1:e8:1e:0f:bd:e3:55:cd:b4:54:8b:1c"]
      # - attach_workspace:
      #     at: ~/
      - run:
          name: install ansible dependencies on ubuntu
          command: |
            apk add --update ansible
#            apt-get install -y tar gzip
            apk add --update nodejs npm
            apk add --update npm
            echo npm --version
          # sudo apt update
          # sudo apt install ansible
#            apt-get install -y tar gzip
      - run: 
          name: Deploy backend
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  default:
    jobs:         
      - deploy-backend            