version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/project
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout

  test:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
