version: 2.1

jobs:
  build:
    working_directory: ~/project
    # Reuse Docker container specification given by the node Orb
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: print hellow
          command: echo "hellow"

  test:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/base:stable
    steps:
      - checkout
      - echo "this is test"

  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-west-2
workflows:
  build_and_test_infa:
    jobs:
      - build
      - test:
          requires:
            - build
      - create_infrastructure
